---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: linux
    image: ${namespace:-diodonfrost}/${distribution:-ansible-centos:8}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
    env:
      ohmyzsh_theme: "${ohmyzsh_theme:-robbyrussell}"
      ohmyzsh_plugins: "${ohmyzsh_plugins:-git}"
provisioner:
  name: ansible
verifier:
  name: ansible
