name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.image }} ohmyzsh ${{ matrix.ohmyzsh_theme }} ${{ matrix.ohmyzsh_plugins }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ansible-centos:8
          - ansible-centos:7
          - ansible-centos:6
          - ansible-fedora:32
          - ansible-fedora:31
          - ansible-fedora:30
          - ansible-fedora:29
          - ansible-fedora:28
          - ansible-fedora:27
          - ansible-fedora:26
          - ansible-ubuntu:20.04
          - ansible-ubuntu:18.04
          - ansible-ubuntu:16.04
          - ansible-ubuntu:14.04
          - ansible-ubuntu:12.04
          - ansible-debian:10
          - ansible-debian:9
          - ansible-debian:8
          - ansible-oraclelinux:8
          - ansible-oraclelinux:7
          - ansible-oraclelinux:6
          - ansible-amazonlinux:2
          - ansible-amazonlinux:1
          - ansible-opensuse:leap
          - ansible-opensuse:tumbleweed
          - ansible-archlinux:latest
          - ansible-alpine:latest
        ohmyzsh_theme:
          - intheloop
          - jispwoso
        ohmyzsh_plugins:
          - "git,docker,systemd"
          - "rails,git,ruby"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Ansible role
        run: |
          image=${{ matrix.image }} ohmyzsh_theme=${{ matrix.ohmyzsh_theme }} ohmyzsh_plugins=${{ matrix.ohmyzsh_plugins }} molecule test
